name: 'Setup Pip with Version Constraint'
description: 'Install pip with a specific version constraint'
inputs:
  pip-version:
    description: 'Pip version constraint (e.g., "pip < 25.3")'
    required: false
    default: 'pip < 25.3'
runs:
  using: 'composite'
  steps:
    - name: Ensure pip version, install pipx, hatch, etc.
      shell: bash
      env:
        PIPX_DEFAULT_VENV_CREATE_SYSTEM: '1'  # make sure that PIX defaults to installed pip version
        PIPX_HOME: "${{ github.workspace }}/.pipx"
      run: |
        python -m pip install --upgrade "${{ inputs.pip-version }}" pipx
        pipx install pre-commit
        pipx inject pre-commit "${{ inputs.pip-version }}"
        pipx install hatch
        pipx inject hatch hatch-vcs hatch-pip-compile "${{ inputs.pip-version }}"
        pipx list --include-injected
