from __future__ import annotations

import pytest

import ultimate_notion as uno
from ultimate_notion import Session
from ultimate_notion.page import Page


@pytest.mark.vcr()
def test_headings(root_page: Page, notion: Session):
    page = notion.create_page(parent=root_page, title='Autogenerated page')
    h1 = uno.Heading1('My new page')
    page.append(h1)

    # check if appending does not lead to doublicate appending.
    # check what happens after a relead() call
