name: CVR Rewrite

on:
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch to commit to (optional for PRs)'
        required: false
        default: ''

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: "1"
  FORCE_COLOR: "1"
  NOTION_TOKEN: "${{ secrets.NOTION_AUTH_TOKEN }}"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    environment:
        name: manual-approval
    name: Python 3.10 on Ubuntu

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch_name || github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Hatch & pre-commit
      run: |
        pip install --upgrade hatch hatch-vcs pre-commit
        pip list

    - name: Lint
      run: hatch run lint:all

    - name: Run tests & rewrite cassettes
      run: hatch run vcr-rewrite

    # Automatic Commit Step
    - name: Auto Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Automated commit by GitHub Actions"
        branch: ${{ github.head_ref }}
        commit_user_name: "GitHub Actions"
        commit_user_email: "actions@github.com"
